language: c

before_script:
  - wget -O astyle_2.04_linux.tar.gz http://sourceforge.net/projects/astyle/files/astyle/astyle%202.04/astyle_2.04_linux.tar.gz/download
  - tar -xf astyle_2.04_linux.tar.gz -C $HOME
  - make -C $HOME/astyle/build/gcc
  - make -C $HOME/astyle/build/gcc prefix=$HOME install
script:
  - if [[ -n $(make astyle | grep Formatted) ]]; then echo "Code formatting error. Please check astyle"; exit -1; fi
  - make clean
  - make
